apiVersion: v1
kind: Service
metadata:
  name: digital-kitchen
  namespace: digital-kitchen
spec:
  selector:
    app: digital-kitchen
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
